{% set name = "label-studio-tools" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/label-studio-tools-{{ version }}.tar.gz
    sha256: 2e31698f76293e0b5d83efa2b9bde60e6e6f0e96e58da482b1fc062a1bbfe4b6
  # See https://github.com/heartexlabs/label-studio-tools/pull/31
  - url: https://raw.githubusercontent.com/heartexlabs/label-studio-tools/{{ version }}/requirements.txt
    sha256: a0db321000bf1ff6fc6844988d5554a11b0951587c57eb457f7cc0a15acbff55
    fn: requirements.txt


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs >=1.4.3
    - lxml >=4.2.5
    - python >=3.6

test:
  imports:
    - label_studio_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/heartexlabs/label-studio-tools
  summary: Label studio common tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
